### PR TITLE
[Test Needed] 1.2

### PR DESCRIPTION
**Pull request by wfjsw**
Local test ok, need more tests.
CC @cachethq/owners @cachethq/docker 

P.S. build `base-d3506c1` from d3506c1ad7af80933cb97bfa60c48a00ccb00f45 first!

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We don't want to support 1.1 at all.

**Comment by GrahamCampbell** [comment]
We only want 1.2 support in this repo for now, and nothing else.

**Comment by wfjsw** [comment]
This is bumped to 1.2

**Comment by rtrauntvein** [comment]
lgtm

**Pull request merged**
