### PR TITLE
Allow building against releases with VERSION

### PR DESCRIPTION
**Pull request by dhorbach**
Added env variable so that builds can be done against releases like "v2.2.1"

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Oh yeah, we definitely shouldn't be shipping `master`.

**Comment by GrahamCampbell** [comment]
The master branch is meant to be master for development here.

**Comment by GrahamCampbell** [comment]
We can't just allow people to set custom versions, because the environment requirements are not necessarily the same between versions.

**Comment by GrahamCampbell** [comment]
To get specific releases, uses the tags on this repo: https://github.com/CachetHQ/Docker/releases

**Comment by dhorbach** [comment]
Ok got it - thanks

**Pull request closed without merging**
