### PR TITLE
Added CACHET_BEACON env as false by default

### PR DESCRIPTION
**Pull request by PauloPaquielli**
I recently had a problem with the cachet load time.

By doing some tests, the configuration of the beacons appears to have degraded performance.

pasted image at 2017_03_29 05_50 pm

When I set the option to false, it had a different grid.

pasted image at 2017_03_30 09_51 am

I think we could keep this option as false.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Interesting. The beacon runs in a scheduled task so should have no detrimental performance effects.

**Comment by jbrooksuk** [comment]
I'll investigate loads when I'm back from holiday. But this setting will remain on by default :)

**Comment by GrahamCampbell** [comment]
I would assume this is because you are using the null cache driver perhaps? Is this only happening on first load?

**Comment by jbrooksuk** [comment]
Also, I notice in your screenshot that you have different system statuses. It could be a performance thing on our code that calculates this.

_I couldn't see this before on limited internet._

**Comment by PauloPaquielli** [comment]
Hello Guys @jbrooksuk @GrahamCampbell ,

I spent about 3 days trying to debug what this performance problem would be. I put a server with 4cpu / 4gb and still it was very slow. I realized that it was not a resource problem. And I went to solve the environment variables. As soon as I put the environment variable "CACHET_BEACON" with false it gave an incredible improvement in the performance. I do not know if it would be a problem with the server's internal firewall. But to me what solved was this: /

```

**Pull request closed without merging**
