### PR TITLE
Switch to php7.0

### LINKED ISSUE #38: Upgrade to PHP 7 for 2.1.0

### PR DESCRIPTION
**Pull request by djdefi**
Switched to `debian:sid` so we can get onto php 7 :zap: 

Closes #38

### CODE REVIEW

**Comment by jbrooksuk** [comment]
This was merged, but we're still using PHP 5?

**Comment by djdefi** [comment]
@jbrooksuk I reverted this due to lack of ubuntu or debian official PHP7 package, and no APCu module in php7

Happy to revisit this but it was not working well at the time.

**Comment by GrahamCampbell** [comment]
> I reverted this due to lack of ubuntu or debian official PHP7 package, and no APCu module in php7

The offical packages normally lag behind by about 2 years with fixes anyways. :) Also, APC is available now I think.

**Comment by djdefi** [comment]
Could be, it was a lot of piping curl's to bash and ugly tutorials to get it even installed in Debian Sid. I was not ever able to get Cachet to come back after a restart (may have been something else that has been fixed recently)

What distro and php7 install guides are you guys using for development? We can try to reproduce that in our Dockerfile.

**Comment by jbrooksuk** [comment]
I use Laravel Homestead :)

**Comment by djdefi** [comment]
Looks like that is going to take some reverse engineering, as they are using a customized [Vagrant box and provisioning scripts](https://github.com/laravel/homestead/blob/f70ef359bbdca5f39165a24b6f0a2d75e72616c2/scripts/homestead.rb#L16).

**Pull request merged**
