### PR TITLE
Cachet Helm Chart

### PR DESCRIPTION
**Pull request by gregdhill**
Signed-off-by: greg <greg.hill@monax.io>

Adds a helm chart for easily deploying a cachet instance to a Kubernetes cluster.

### CODE REVIEW

**Comment by phutchins** [comment]
Would be awesome to get this merged.

**Comment by djdefi** [comment]
I’m not running Cachet in Kubernetes, so I’m not really a great reviewer for the technical side here.

Is there a benefit to keeping these service definition type files in this repo? If they are not _required_ to come from the same repo, I might suggest maintaining these separately. We would be happy to link to these deployment options in our Readme for visibility.

**Comment by phutchins** [comment]
In that case @gregdhill you might submit them here: https://github.com/helm/charts/tree/master/stable

**Comment by djdefi** [comment]
Is https://github.com/CachetHQ/Docker/pull/154 similar here? I’m not sure how openshift and helm charts overlap (pardon my ignorance on this subject).

**Comment by phutchins** [comment]
Similar that they both assist in deploying Cachet to a platform, however the container platform is completely different. Helm is Kubernetes and Openshift is a RedHat thing.

**Comment by gregdhill** [comment]
Closing this as I've submitted a generic status page Helm Chart into incubation: https://github.com/helm/charts/pull/12824

**Pull request closed without merging**
