### PR TITLE
Update Dockerfile from v1.2.0 to v2.0.0-RC2

### PR DESCRIPTION
**Pull request by andygrunwald**
Update the Dockerfile to latest (pre) release

### CODE REVIEW

**Comment by andygrunwald** [comment]
Updated to v2.0.0-RC2

**Comment by GrahamCampbell** [comment]
We actually need 1.2.0 -> 1.2.1 -> 2.0.0-beta1 -> 2.0.0-beta2 -> 2.0.0-RC1 -> 2.0.0-RC2 so each can be marked as releases.

**Comment by GrahamCampbell** [comment]
Ping @cachethq/docker. :)

**Comment by andygrunwald** [comment]
I would tag and push them, when i could ;)

**Comment by dereckson** [comment]
GD is missing.

```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pragmarx/google2fa v0.7.0 requires simplesoftwareio/simple-qrcode 1.3.* -> satisfiable by simplesoftwareio/simple-qrcode[1.3.0, 1.3.1].
    - pragmarx/google2fa v0.7.1 requires simplesoftwareio/simple-qrcode 1.3.* -> satisfiable by simplesoftwareio/simple-qrcode[1.3.0, 1.3.1].
    - simplesoftwareio/simple-qrcode 1.3.1 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - simplesoftwareio/simple-qrcode 1.3.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - Installation request for pragmarx/google2fa ^0.7 -> satisfiable by pragmarx/google2fa[v0.7.0, v0.7.1].
```

**Comment by jbrooksuk** [comment]
We'll need to update to 2.0.2 now.

**Comment by djdefi** [comment]
Added the releases `2.0.0, 2.0.1, 2.0.2`

Also updated `latest` to utilize latest base image and "master" from upstream Cachet repo.

I am not going to do the RC releases here, already have enough tags on docker hub to keep track of.

**Pull request closed without merging**
