### PR TITLE
Added database migrate and keygeneration as startup action

### PR DESCRIPTION
**Pull request by andygrunwald**
Checkout https://github.com/CachetHQ/Docker/issues/36 for details.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is incorrect, we should never be running those commands. We should only interface with `php artisan app:install` or `php artisan app:update`.

**Comment by andygrunwald** [comment]
@GrahamCampbell Sorry, but i am a little bit pissed because of your tone and your behaviour. In my opinion this is not the way how to treat contributer.

1. Why don`t let this PR open and provide the chance that the contributor can fix / modify the issues?

2. Why not elaborate a little bit more what is "incorrect" in detail? Maybe not all people who are using Laravel on a daily basis like you and you know what they are doing? They are using the documentation of Cachet (because for an enduser it don`t matter if Cachet is build upon Laravel).
In the documentation all those three commands are mentioned and i can`t see a occurrence of `php artisan app:install` or `php artisan app:update`.
Checkout

* https://docs.cachethq.io/docs/get-started-with-docker
* https://docs.cachethq.io/docs/installing-cachet
* https://docs.cachethq.io/docs/updating-cachet

3. Is `php artisan app:install` a shortcut for all three commands? Or does this only replace one of those commands?

4. What is your way to fix this issue described in #36? Maybe you can help to describe it to raise the chance to get such a change in.

Don`t make it harder to contribute to OSS as it already is.

**Comment by GrahamCampbell** [comment]
1. No, just send a new PR if you want to continue it, otherwise closing it frees it from our list of things to manage.

2. Our `app:` commands are used for installing/updating cachet. If they don't work properly, we'd accept PRs to the main cachet repo

3. No, not really.

4. If our install/update commands are not getting run, then they need to be.

**Comment by GrahamCampbell** [comment]
> Don`t make it harder to contribute to OSS as it already is.

Don't mean to be a dick, but it's never been easier to contribute to OSS than it is today.

**Comment by andygrunwald** [comment]
To be honest: I don`t have a clue where is the difference between the install / upgrade command and the commands mentioned in the documentation and in this PR.
Because IMO you answered not really the question how i should continue with it.
But in the end it seems that you are not interested in contributor or getting a big(ger) userbase for cachet. This is sad.

I am thinking about to stop contributing to this project.

**Comment by djdefi** [comment]
`artisan app:install` and `php artisan app:update` are not mentioned anywhere in the Cachet docs install or main repo.  

Not sure how we can be expected to know to use these commands when they are nowhere to be found in the documentation.

**Comment by jbrooksuk** [comment]
Docs need to be updated. It's just finding time I'm afraid :(

**Pull request closed without merging**
