### PR TITLE
Fixes issue where .env file is invalid

### LINKED ISSUE #60: Container won't start
Hey guys, just grabbed the latest version and I'm getting the following error when starting the container:

```
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
Generating optimized class loader
Compiling common classes
> php artisan config:cache
Configuration cache cleared!


  [Dotenv\Exception\InvalidFileException]
  Dotenv values containing spaces must be surrounded by quotes.


Script php artisan config:cache handling the post-install-cmd event returned with an error


  [RuntimeException]
  Error Output:


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('config')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('config', Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('config', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('config')
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1223): Illuminate\Container\Container->offsetGet('config')
#5 /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(46): Illuminate\Container\Container->__get('config')
#6 [internal function]: GrahamCampbell\Exceptions in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 738
Script php artisan optimize --force handling the post-install-cmd event returned with an error
```

Because of the container restart policy it keeps rebooting with the same error

### PR DESCRIPTION
**Pull request by adamlc**
This fixes #60 where the .env file is created without quotes

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Most of these settings should never need to be double-quoted, but if it works then it's only going to prevent issues further down the line 👍

**Comment by adamlc** [comment]
Ill be honest I didn't think all of them would need to be, but I guess it won't hurt though 😄

**Comment by djdefi** [comment]
Interesting find. 

```
Dotenv values containing spaces must be surrounded by quotes.
```

Out of curiosity, which attribute were you using a space in?

**Comment by jbrooksuk** [comment]
Usually it's `MAIL_NAME` that causes an issue.

**Comment by adamlc** [comment]
Yeah it was just MAIL_NAME actually. I guess thats probably the only one that will need double quotes. I'm not sure if theres a better way of doing this in the entrypoint script?

**Comment by jbrooksuk** [comment]
This is probably the simplest place.

**Comment by adamlc** [comment]
Shall I modify the PR to only change the ```MAIL_NAME```?

**Comment by jbrooksuk** [comment]
It's possible that `MAIL_PASSWORD` could have a space.

**Comment by adamlc** [comment]
Well does it hurt leaving them all double quoted?

**Comment by jbrooksuk** [comment]
Not that I know of.

**Comment by mattallty** [comment]
It hurts: see https://github.com/CachetHQ/Docker/pull/151

**Pull request merged**
