### PR TITLE
set better security defaults in docker-compose.yml

### LINKED ISSUE #337: docker-compose config should be secure by default
Currently, the docker compose configuration doesn't set `APP_DEBUG=false`, or `APP_ENV=production`. This means a user accessing even something as simple as a page that doesn't exist (404) will see all environment variables, including database credentials, and other sensitive information, due to the Symfony exception page.

### PR DESCRIPTION
**Pull request by lrstanley**
Without `APP_DEBUG=false` or `APP_ENV=production`, this may lead to unwanted exposure of environment variables when a user hits an exception (or even a 404). With docker specifically, these environment variables also include the database credentials. This change will ensure this debugging functionality is not enabled by default.

Resolves: https://github.com/CachetHQ/Docker/issues/337

### CODE REVIEW

**Comment by djdefi** [comment]
Hmm maybe we were parsing some debug only output in the tests, will have to take a look at what happens when running the test steps manually on a local copy. 

I’m not sure if I’ll be able to test this week myself; but thanks for getting this started!

**Comment by lrstanley** [comment]
Original thought was potentially overriding them via docker-compose when running up, but only looks like it's supported via run (https://docs.docker.com/compose/environment-variables/). Could drop in a .env specifically for testing to override, or do `${ENV:-substitute}`.. or could always just run something like this in travisci before actually running the tests:

```console
$ sed -ri "/- (APP_ENV|APP_DEBUG)=/d" docker-compose.yml
```

The above command finds lines matching that regex and will just delete them. :man_shrugging:

**Comment by lrstanley** [comment]
Had a chance to look at this @djdefi?

**Comment by djdefi** [comment]
Sorry for the delay. 

I think what we can do here is set https://github.com/CachetHQ/Docker/blob/master/entrypoint.sh#L75 to `false` so that is the default, and then remove the APP_DEBUG setting from the `docker-compose.yml` file entirely. That way we can enable it just in the CI env.

**Pull request merged**
