### PR TITLE
Switch docker-compose.yml to use pgsql

### LINKED ISSUE #2: Switch to PostgreSQL
Will need to swap this out in the `docker-compose.yml` and make sure the correct ENV variables are set

### PR DESCRIPTION
**Pull request by djdefi**
Change to `docker-compose.yml` to utilize postgresql instead of MySQL. Does not require immediately updating docs, since MySQL will still work fine also.

Closes #2

### CODE REVIEW

**Comment by rtrauntvein** [comment]
ping @cachethq/docker

**Comment by n0mer** [comment]
@rtrauntvein so what exactly do you want

and why do you change to pgsql

**Comment by rtrauntvein** [comment]
Just looking for review of the PR.

This is based on suggestion of using Postgres instead of MySQL by @GrahamCampbell or @jbrooksuk

**Comment by GrahamCampbell** [comment]
> and why do you change to pgsql

Because it's way better than mysql. ;P

**Comment by n0mer** [comment]
it is less popular , according to http://db-engines.com/en/ranking

image

**Comment by GrahamCampbell** [comment]
> it is less popular

Doesn't mean it's not better.

**Comment by jbrooksuk** [comment]
In our experience - with StyleCI - MySQL has a lot of quirks that we can avoid.

**Comment by n0mer** [comment]
i would quote Donald E. Knuth here, "premature optimization is root of all evil".

If your users demand this - fine.

If this to show off your personal taste - you're on your own :)

**Comment by n0mer** [comment]
@rtrauntvein as for PR itself - why did you change data-only container to the folder on host machine?

**Comment by rtrauntvein** [comment]
There was no data volume or data only container for persistence of the Database before.

**Comment by n0mer** [comment]
@rtrauntvein you are right, no volumes for compose. You just hardcoded the path on host machine, that this "compose" script will demand.

**Comment by rtrauntvein** [comment]
The directory would get created automatically, but I will just take it out.

**Comment by GrahamCampbell** [comment]
Any news on this?

**Pull request merged**
