### PR TITLE
Missing predis/predis compose dependency when running when running wi…

### PR DESCRIPTION
**Pull request by crashdump**
This PR address a missing library ("predis/predis") when running in Redis mode.

### CODE REVIEW

**Comment by djdefi** [comment]
I am not entirely sure on best practices here, does it make sense to add this dependency to the [Cachet `composer.json`](https://github.com/CachetHQ/Cachet/blob/2.4/composer.json) rather than as a global include? 

cc: @jbrooksuk @GrahamCampbell

**Comment by jbrooksuk** [comment]
But Cachet itself [already requires](https://github.com/CachetHQ/Cachet/blob/3d2523886a606f9f9d2a06a2a053187941af1c95/composer.json#L52) `predis/predis`.

**Comment by crashdump** [comment]
Interesting as I tried to start the container with QUEUE_DRIVER to Radius.

```
2017-03-24T09:11:51.596426769Z 2017-03-24 09:11:51,596 INFO spawned: 'queue-worker' with pid 65
2017-03-24T09:11:51.722178975Z 2017-03-24 09:11:51,722 INFO exited: queue-worker (exit status 255; not expected)
2017-03-24T09:11:53.724894415Z 2017-03-24 09:11:53,724 INFO spawned: 'queue-worker' with pid 73
2017-03-24T09:11:53.905065235Z 2017-03-24 09:11:53,904 INFO exited: queue-worker (exit status 255; not expected)
2017-03-24T09:11:56.909887427Z 2017-03-24 09:11:56,909 INFO spawned: 'queue-worker' with pid 81
2017-03-24T09:11:57.100852100Z 2017-03-24 09:11:57,100 INFO exited: queue-worker (exit status 255; not expected)
2017-03-24T09:11:58.101963886Z 2017-03-24 09:11:58,101 INFO gave up: queue-worker entered FATAL state, too many start retries too quickly
```

Diving into the container and trying to start artisan queue:work result in:

$ php artisan queue:work --delay=2 --sleep=1 --tries=3

```
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Predis\Client' not found         
```

**Comment by crashdump** [comment]
Further investigations below.

```
$ ls -la vendor/ | grep predis
```

```
$ php composer.phar require "predis/predis:^1.1"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing predis/predis (v1.1.1)
    Loading from cache
[...]
predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize --force
Generating optimized class loader
Compiling common classes
> php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
> php artisan route:cache
Route cache cleared!
Routes cached successfully!
```

```
$ php composer.phar install --no-dev -o
[...]
```

```
ls -la vendor/ | grep predis
drwxr-xr-x  3 www-data www-data 4096 Mar 24 09:53 predis
```

```
$ php artisan queue:work --delay=2 --sleep=1 --tries=3
$ echo $?
0
```

Success !

**Comment by crashdump** [comment]
Right, it seem cachet's compose.json on the master branch does not include  _predis/predis_ (but as @jbrooksuk mentioned earlier, it's present on "2.4")..

I am closing my PR and will be patient... wait for 2.4 to be merged back into master. Thanks.

**Comment by jbrooksuk** [comment]
I need to backport some changes into 2.3 so I'll make sure this is one of them.

**Comment by crashdump** [comment]
Thanks @jbrooksuk, that would be great!

**Pull request closed without merging**
